#!/usr/bin/env node

/**
 * CargoFlow Tunnel Deployment Automator
 *
 * Reads temporary tunnel credentials from apps/web/.env.tunnel.local (generated by npm run tunnel:api)
 * and deploys the OpenNext Cloudflare Worker configured to that tunnel endpoint.
 */

import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const webDir = path.join(rootDir, 'apps', 'web');
const envTunnelPath = path.join(webDir, '.env.tunnel.local');

console.log('='.repeat(70));
console.log('🚀 CargoFlow — Cloudflare Worker Deploy with Tunnel Endpoint');
console.log('='.repeat(70));

if (!fs.existsSync(envTunnelPath)) {
  console.error('\n❌ No active tunnel configuration found at apps/web/.env.tunnel.local.');
  console.error('   Please launch the Quick Tunnel first in another terminal:');
  console.error('   npm run tunnel:api\n');
  process.exit(1);
}

const envContent = fs.readFileSync(envTunnelPath, 'utf-8');
const apiMatch = envContent.match(/NEXT_PUBLIC_API_URL=(.+)/);
const wsMatch = envContent.match(/NEXT_PUBLIC_WS_URL=(.+)/);

if (!apiMatch || !apiMatch[1].trim()) {
  console.error('\n❌ Could not find NEXT_PUBLIC_API_URL in apps/web/.env.tunnel.local.');
  process.exit(1);
}

const apiUrl = apiMatch[1].trim();
const wsUrl = (wsMatch ? wsMatch[1].trim() : apiUrl.replace(/^http/, 'ws').replace(/\/api$/, ''));

console.log(`\nActive Tunnel Configuration Detected:`);
console.log(`- API URL: ${apiUrl}`);
console.log(`- WS URL:  ${wsUrl}\n`);

function runCommand(cmd, args, cwd, env = {}) {
  return new Promise((resolve, reject) => {
    console.log(`> ${cmd} ${args.join(' ')}`);
    const proc = spawn(cmd, args, {
      cwd,
      stdio: 'inherit',
      shell: process.platform === 'win32',
      env: { ...process.env, ...env },
    });

    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Command failed with exit code ${code}`));
    });

    proc.on('error', (err) => reject(err));
  });
}

async function deploy() {
  const npxCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';

  console.log('--- Step 1: Building OpenNext Cloudflare Worker ---');
  await runCommand(
    npxCmd,
    ['opennextjs-cloudflare', 'build'],
    webDir,
    {
      NEXT_PUBLIC_API_URL: apiUrl,
      NEXT_PUBLIC_WS_URL: wsUrl,
      NODE_ENV: 'production',
    }
  );

  console.log('\n--- Step 2: Deploying Worker to Cloudflare ---');
  await runCommand(
    npxCmd,
    [
      'wrangler',
      'deploy',
      '--var',
      `NEXT_PUBLIC_API_URL:${apiUrl}`,
      '--var',
      `NEXT_PUBLIC_WS_URL:${wsUrl}`,
      '--keep-vars',
    ],
    webDir,
    {
      NEXT_PUBLIC_API_URL: apiUrl,
      NEXT_PUBLIC_WS_URL: wsUrl,
    }
  );

  console.log('\n' + '='.repeat(70));
  console.log('🎉 Cloudflare Worker Successfully Deployed with Quick Tunnel Endpoint!');
  console.log('='.repeat(70));
  console.log('Live Frontend: https://3d-truck.sreehariradhakrishnan2000.workers.dev');
  console.log(`Connected to:  ${apiUrl}`);
  console.log('='.repeat(70) + '\n');
}

deploy().catch((err) => {
  console.error(`\n❌ Deployment failed: ${err.message}\n`);
  process.exit(1);
});

