#!/usr/bin/env node

/**
 * CargoFlow Tunnel Deployment Automator
 *
 * Reads temporary tunnel origin from apps/web/.env.tunnel.local (generated by npm run tunnel:api)
 * and deploys the OpenNext Cloudflare Worker configured to proxy /api/* and /ws to that tunnel origin.
 */

import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const webDir = path.join(rootDir, 'apps', 'web');
const envTunnelPath = path.join(webDir, '.env.tunnel.local');

console.log('='.repeat(70));
console.log('🚀 CargoFlow — Cloudflare Worker Deploy with Single Public Gateway');
console.log('='.repeat(70));

if (!fs.existsSync(envTunnelPath)) {
  console.error('\n❌ No active tunnel configuration found at apps/web/.env.tunnel.local.');
  console.error('   Please launch the Quick Tunnel first in another terminal:');
  console.error('   npm run tunnel:api\n');
  process.exit(1);
}

const envContent = fs.readFileSync(envTunnelPath, 'utf-8');
const originMatch = envContent.match(/BACKEND_API_ORIGIN=(.+)/) || envContent.match(/NEXT_PUBLIC_API_URL=(.+)/);

if (!originMatch || !originMatch[1].trim()) {
  console.error('\n❌ Could not find BACKEND_API_ORIGIN in apps/web/.env.tunnel.local.');
  process.exit(1);
}

let backendOrigin = originMatch[1].trim().replace(/\/+$/, '');
// Strip trailing /api if present
backendOrigin = backendOrigin.replace(/\/api$/, '');

console.log(`\nActive Tunnel Configuration Detected:`);
console.log(`- Backend Proxy Origin: ${backendOrigin}`);
console.log(`- Public Gateway URL:   https://3d-truck.sreehariradhakrishnan2000.workers.dev`);
console.log(`- Browser API Path:     /api/* (Same Origin)`);
console.log(`- Browser WS Path:      /ws (Same Origin)\n`);

function runCommand(cmd, args, cwd, env = {}) {
  return new Promise((resolve, reject) => {
    console.log(`> ${cmd} ${args.join(' ')}`);
    const proc = spawn(cmd, args, {
      cwd,
      stdio: 'inherit',
      shell: process.platform === 'win32',
      env: { ...process.env, ...env },
    });

    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Command failed with exit code ${code}`));
    });

    proc.on('error', (err) => reject(err));
  });
}

async function deploy() {
  const npxCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';

  console.log('--- Step 1: Building OpenNext Cloudflare Worker ---');
  await runCommand(
    npxCmd,
    ['opennextjs-cloudflare', 'build'],
    webDir,
    {
      NODE_ENV: 'production',
      BACKEND_API_ORIGIN: backendOrigin,
      NEXT_PUBLIC_API_URL: '/api',
    }
  );

  console.log('\n--- Step 2: Deploying Worker to Cloudflare ---');
  await runCommand(
    npxCmd,
    [
      'wrangler',
      'deploy',
      '--var',
      `BACKEND_API_ORIGIN:${backendOrigin}`,
      '--keep-vars',
    ],
    webDir,
    {
      BACKEND_API_ORIGIN: backendOrigin,
      NEXT_PUBLIC_API_URL: '/api',
    }
  );

  console.log('\n' + '='.repeat(70));
  console.log('🎉 Cloudflare Worker Successfully Deployed with Single Public Gateway!');
  console.log('='.repeat(70));
  console.log('Public URL:   https://3d-truck.sreehariradhakrishnan2000.workers.dev');
  console.log('API Path:     https://3d-truck.sreehariradhakrishnan2000.workers.dev/api');
  console.log('WS Path:      wss://3d-truck.sreehariradhakrishnan2000.workers.dev/ws');
  console.log(`Proxied to:   ${backendOrigin}`);
  console.log('='.repeat(70) + '\n');
}

deploy().catch((err) => {
  console.error(`\n❌ Deployment failed: ${err.message}\n`);
  process.exit(1);
});
