#!/usr/bin/env node

/**
 * Cloudflare Quick Tunnel Automator for CargoFlow API
 * 
 * Exposes local/containerized NestJS API (port 3001) over a free, temporary
 * Cloudflare Quick Tunnel (*.trycloudflare.com).
 * 
 * IMPORTANT: Quick Tunnels are temporary and suitable for testing/preview only.
 * They are NOT permanent production infrastructure.
 */

import { spawn } from 'child_process';
import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const envTunnelPath = path.join(rootDir, 'apps', 'web', '.env.tunnel.local');

const API_PORT = process.env.PORT || 3001;
const LOCAL_TARGET = `http://localhost:${API_PORT}`;

console.log('='.repeat(60));
console.log('🚀 CargoFlow — Cloudflare Quick Tunnel Automator');
console.log('='.repeat(60));
console.log(`Targeting local backend at: ${LOCAL_TARGET}`);

function checkLocalBackend(port) {
  return new Promise((resolve) => {
    const req = http.request(
      {
        hostname: '127.0.0.1',
        port: port,
        path: '/api/health',
        method: 'GET',
        timeout: 1500,
      },
      (res) => {
        resolve(res.statusCode < 500);
      }
    );
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
    req.end();
  });
}

async function start() {
  const isUp = await checkLocalBackend(API_PORT);
  if (!isUp) {
    console.warn(`\n⚠️  Notice: Local API does not appear to be running on port ${API_PORT}.`);
    console.warn(`   You can start it in another terminal with: npm run dev:api (or docker compose up api)`);
  } else {
    console.log(`✅ Local API detected running on port ${API_PORT}.`);
  }

  console.log(`\n⏳ Initiating Cloudflare Quick Tunnel (npx wrangler tunnel quick-start)...`);
  console.log(`   (This provides a free temporary trycloudflare.com URL without an account)\n`);

  const cmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';
  const args = ['wrangler', 'tunnel', 'quick-start', LOCAL_TARGET];

  const tunnelProc = spawn(cmd, args, {
    cwd: rootDir,
    stdio: ['inherit', 'pipe', 'pipe'],
    shell: process.platform === 'win32',
  });

  let tunnelDetected = false;
  let tunnelUrl = '';

  const processOutput = (data) => {
    const text = data.toString();
    process.stdout.write(text);

    if (!tunnelDetected) {
      const match = text.match(/https:\/\/[a-zA-Z0-9-]+\.trycloudflare\.com/);
      if (match) {
        tunnelDetected = true;
        tunnelUrl = match[0];
        onTunnelReady(tunnelUrl);
      }
    }
  };

  tunnelProc.stdout.on('data', processOutput);
  tunnelProc.stderr.on('data', processOutput);

  tunnelProc.on('error', (err) => {
    console.error(`\n❌ Failed to start tunnel process: ${err.message}`);
    process.exit(1);
  });

  tunnelProc.on('exit', (code) => {
    console.log(`\n🛑 Tunnel process exited with code ${code}.`);
    process.exit(code || 0);
  });

  function onTunnelReady(url) {
    const envContent = [
      '# ============================================================',
      '# CARGOFLOW CLOUDFLARE QUICK TUNNEL PREVIEW CONFIGURATION',
      '# Auto-generated by: npm run tunnel:api',
      `# Generated at: ${new Date().toISOString()}`,
      '#',
      '# WARNING: Quick Tunnels (*.trycloudflare.com) are TEMPORARY',
      '# for testing and preview only. NOT FOR PERMANENT PRODUCTION.',
      '# ============================================================',
      `BACKEND_API_ORIGIN=${url}`,
      `NEXT_PUBLIC_API_URL=/api`,
      '',
    ].join('\n');

    fs.writeFileSync(envTunnelPath, envContent, 'utf-8');

    console.log('\n' + '='.repeat(60));
    console.log('🎉 CLOUDFLARE QUICK TUNNEL ESTABLISHED');
    console.log('='.repeat(60));
    console.log(`Backend Origin:      ${url}`);
    console.log(`Worker Gateway URL:  https://3d-truck.sreehariradhakrishnan2000.workers.dev`);
    console.log(`Browser API URL:     https://3d-truck.sreehariradhakrishnan2000.workers.dev/api`);
    console.log(`Browser WS URL:      wss://3d-truck.sreehariradhakrishnan2000.workers.dev/ws`);
    console.log('='.repeat(60));
    console.log(`📁 Saved temporary configuration to:`);
    console.log(`   ${path.relative(rootDir, envTunnelPath)}`);
    console.log('');
    console.log('📋 Next steps to connect Cloudflare Worker to this tunnel:');
    console.log('   Option A (Automated Deploy):');
    console.log('      npm run deploy:tunnel');
    console.log('   Option B (Cloudflare Dashboard - no rebuild):');
    console.log('      In Cloudflare Dashboard → Workers → 3d-truck → Settings → Variables,');
    console.log(`      Set BACKEND_API_ORIGIN = ${url}`);
    console.log('   Run diagnosis anytime:');
    console.log('      npm run diagnose:deployment');
    console.log('='.repeat(60) + '\n');
  }

  const cleanup = () => {
    console.log('\n🛑 Stopping Cloudflare Quick Tunnel...');
    if (tunnelProc && !tunnelProc.killed) {
      tunnelProc.kill();
    }
    process.exit(0);
  };

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);
}

start();

